/* Bibliothèque : tous les exercices du catalogue, filtrables par muscle, type, matériel et zone de soin.
   Repris de l'écran supprimé au lot 9 (commit 385d5df), avec le filtre « Soin » branché sur les protocoles de rehab-warmup.js. */
function PTMuscleExplorer({value,onChange}){
  const [back,setBack]=usePTState(false);
  return <section className="muscle-explorer"><div className="muscle-copy"><span className="eyebrow">Filtrer par muscle</span><h2>{value==='all'?<>QUEL<br/>MUSCLE ?</>:ptMuscleLabels[value]}</h2><p className="fine">Touche une zone.</p><button className="chip rotate-body" onClick={()=>setBack(!back)}><PTIcon name="refresh" size={16}/>{back?'Voir de face':'Voir de dos'}</button><button className="text-button muscle-reset" aria-hidden={value==='all'} disabled={value==='all'} tabIndex={value==='all'?-1:undefined} onClick={()=>onChange('all')}>Tout afficher</button></div><PTBodyMap selected={value} onSelect={onChange} back={back}/></section>;
}
// Ids utilisés par les protocoles de soin d'une zone (tous niveaux confondus).
function ptCareIds(zone){
  const RW=window.RehabWarmup;if(!RW||zone==='all')return null;
  return new Set(RW.protocols.filter(p=>p.zone===zone).flatMap(p=>p.levels.flat().flatMap(slot=>Array.isArray(slot)?slot:slot.ids)));
}
function PTLibrary({data,update,go,notify}) {
  const [query,setQuery]=usePTState(''),[kind,setKind]=usePTState('all'),[open,setOpen]=usePTState(null),[adding,setAdding]=usePTState(false),[error,setError]=usePTState('');
  const [muscle,setMuscle]=usePTState('all'),[equipment,setEquipment]=usePTState('all'),[care,setCare]=usePTState('all');
  const [custom,setCustom]=usePTState({name:'',kind:'strength',pattern:'push',needs:['bodyweight'],regions:[],instructions:'',measure:'reps',min:8,max:12,seconds:30,rest:60,weighted:false,impact:false,level:1});
  const normalize=text=>text.normalize('NFD').replace(/[̀-ͯ]/g,'').toLocaleLowerCase('fr');
  const careIds=ptCareIds(care),RW=window.RehabWarmup;
  const items=PT.allExercises(data).filter(e=>(muscle==='all'||ptMuscles(e).includes(muscle))&&(equipment==='all'||e.needs.includes(equipment))&&(!careIds||careIds.has(e.id))&&(kind==='all'||kind==='liked'&&data.preferences.likes.includes(e.id)||kind==='owned'&&e.needs.every(n=>n==='bodyweight'||data.owned.includes(n))||kind==='basket'&&['shoot','handle','finish','footwork','react','jump'].includes(e.pattern)||e.kind===kind)&&normalize(e.name).includes(normalize(query)));
  const set=(k,v)=>setCustom(c=>({...c,[k]:v}));
  const reset=()=>{setQuery('');setMuscle('all');setEquipment('all');setKind('all');setCare('all');setOpen(null);};
  const add=()=>{if(!custom.name.trim()||!custom.instructions.trim()||!custom.regions.length){setError('Ajoute un nom, des consignes et les zones sollicitées.');return;}const exercise={...custom,id:`custom-${PT.uid()}`,name:custom.name.trim(),instructions:custom.instructions.split('\n').filter(Boolean),min:Number(custom.min),max:Number(custom.max),sets:3,seconds:Number(custom.seconds),rest:Number(custom.rest)};try{PT.validateState({...data,customExercises:[...data.customExercises,exercise]});}catch(e){setError(e.message);return;}update(s=>({...s,customExercises:[...s.customExercises,exercise]}));setAdding(false);setError('');notify('Exercice personnel ajouté au catalogue.');};
  return <div className="library-view"><PTPageHead onBack={()=>history.length>1?history.back():go('pathway')} eyebrow={`${PT.allExercises(data).length} exercices`} title="Tous les exercices."/><div className="stack-lg">
    <PTMuscleExplorer value={muscle} onChange={v=>{setMuscle(v);setOpen(null);}}/>
    <PTField label="Rechercher un exercice" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rowing, squat, cheville…"/>
    <div className="muscle-tabs" role="group" aria-label="Type d’exercice">{[['all','Tous'],['owned','Mon matériel'],['liked','Favoris'],['strength','Force'],['basket','Basket'],['plyo','Pliométrie'],['cardio','Cardio'],['mobility','Mobilité']].map(([value,label])=><button key={value} aria-pressed={kind===value} onClick={()=>{setKind(value);setOpen(null);}}>{label}</button>)}</div>
    <div className="library-filters">
      <PTField label="Matériel"><select value={equipment} onChange={e=>{setEquipment(e.target.value);setOpen(null);}}><option value="all">Tout le matériel</option>{PT.equipment.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></PTField>
      {RW&&<PTField label="Soin d’une zone"><select value={care} onChange={e=>{setCare(e.target.value);setOpen(null);}}><option value="all">Toutes les zones</option>{RW.zones.map(z=><option key={z.id} value={z.id}>{z.label}</option>)}</select></PTField>}
    </div>
    {adding&&<section className="card stack"><h2>Mon mouvement personnel</h2><PTField label="Nom" value={custom.name} maxLength="120" onChange={e=>set('name',e.target.value)}/><div className="form-grid"><PTField label="Famille"><select value={custom.kind} onChange={e=>set('kind',e.target.value)}><option value="strength">Musculation</option><option value="basket">Basket</option><option value="cardio">Cardio</option><option value="mobility">Mobilité</option><option value="plyo">Pliométrie</option></select></PTField><PTField label="Mouvement travaillé"><select value={custom.pattern} onChange={e=>set('pattern',e.target.value)}>{Object.entries(PT.patterns).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></PTField></div><PTField label="Consignes · une par ligne"><textarea value={custom.instructions} maxLength="2000" onChange={e=>set('instructions',e.target.value)}/></PTField><details className="disclosure"><summary>Matériel nécessaire</summary><div><PTEquipment inventory selected={custom.needs} onChange={v=>set('needs',v)}/></div></details><div className="stack-sm"><h3>Zones sollicitées</h3><p className="fine">Sélectionne aussi les articulations d’appui. Ce marquage sert au filtre de douleur ; il ne garantit pas la sécurité.</p><PTChips multi value={custom.regions} options={Object.entries(PT.regions).map(([value,label])=>({value,label}))} onChange={v=>set('regions',v)}/></div><PTField label="Mesure"><select value={custom.measure} onChange={e=>set('measure',e.target.value)}><option value="reps">Répétitions</option><option value="seconds">Secondes</option><option value="shots">Tirs réussis / tentés</option><option value="contacts">Contacts de saut</option></select></PTField><div className="form-grid"><PTField label="Répétitions min." type="number" min="1" max="100" value={custom.min} onChange={e=>set('min',e.target.value)}/><PTField label="Répétitions max." type="number" min="1" max="100" value={custom.max} onChange={e=>set('max',e.target.value)}/><PTField label="Travail (secondes)" type="number" min="1" max="600" value={custom.seconds} onChange={e=>set('seconds',e.target.value)}/><PTField label="Repos (secondes)" type="number" min="0" max="600" value={custom.rest} onChange={e=>set('rest',e.target.value)}/></div><label className="check-label"><input type="checkbox" checked={custom.impact} onChange={e=>set('impact',e.target.checked)}/>Cet exercice comporte des sauts ou des impacts.</label>{error&&<p role="alert" className="error">{error}</p>}<PTButton primary onClick={add}>Ajouter à ma bibliothèque</PTButton></section>}
    <div className="library-toolbar"><button className="icon-button" aria-label={adding?'Fermer l’ajout':'Ajouter mon exercice'} onClick={()=>setAdding(!adding)}><PTIcon name="plus" size={18}/></button><span className="library-count" role="status">{items.length} mouvements</span>{(query||muscle!=='all'||equipment!=='all'||kind!=='all'||care!=='all')&&<button className="text-button" onClick={reset}>Effacer les filtres</button>}</div>
    <div className="exercise-library-grid">{items.map(e=><article className={`exercise-item library-tile${open===e.id?' expanded':''}`} key={e.id}><button className="home-action" onClick={()=>setOpen(open===e.id?null:e.id)} aria-expanded={open===e.id}><PTThumbnail exercise={e}/><span><strong>{e.name}</strong><small>{PT.patterns[e.pattern]} · {e.needs.filter(id=>id!=='bodyweight').map(id=>PT.equipment.find(x=>x.id===id)?.label).join(', ')||'Poids du corps'}{data.preferences.avoids.includes(e.id)?' · écarté des propositions':''}</small></span><PTIcon name="arrow" size={16}/></button>{open===e.id&&<div className="stack"><PTExerciseDetails exercise={e}/><PTChips multi value={[...(data.preferences.likes.includes(e.id)?['like']:[]),...(data.preferences.avoids.includes(e.id)?['avoid']:[])]} options={[{value:'like',label:'J’aime'},{value:'avoid',label:'Ne plus proposer'}]} onChange={values=>update(s=>({...s,preferences:{...s.preferences,likes:values.includes('like')?[...new Set([...s.preferences.likes,e.id])]:s.preferences.likes.filter(id=>id!==e.id),avoids:values.includes('avoid')?[...new Set([...s.preferences.avoids,e.id])]:s.preferences.avoids.filter(id=>id!==e.id)}}))}/></div>}</article>)}</div>
    {!items.length&&<p className="empty">Aucun résultat. Essaie un autre mot, ou efface les filtres.</p>}
  </div></div>;
}
