const CACHE = 'rehaab-v38-refonte';
const PRECACHE = [
  './',
  './index.html',
  './manifest.json',
  './favicon.svg',
  './apple-touch-icon.png',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  './personal.css',
  './live-session.css',
  './sport.css',
  './basket.css',
  './compiled/personal-app.js',
  './compiled/visual-components.js',
  './compiled/sport-components.js',
  './compiled/program-components.js',
  './compiled/player-components.js',
  './compiled/assessment-components.js',
  './compiled/pathway-components.js',
  './compiled/qi-components.js',
  './compiled/video-qi-components.js',
  './compiled/insight-components.js',
  './compiled/live-session.js',
  './exercise-media.js',
  './rehab-warmup.js',
  './compiled/rehab-components.js',
  './vendor/gsap.min.js',
  './vendor/ScrollTrigger.min.js',
  './media/fonts/cabinet.css',
  './media/fonts/cabinet-400.woff2',
  './media/fonts/cabinet-500.woff2',
  './media/fonts/cabinet-700.woff2',
  './media/fonts/cabinet-800.woff2',
  './media/fonts/barlow.css',
  './media/fonts/barlow-0.ttf',
  './media/fonts/barlow-1.ttf',
  './media/training-floor.webp',
  './media/body/front.webp',
  './media/body/back.webp',
  './media/video-credits.json',
  "./media/Pushups/0.webp",
  "./media/Pushups/1.webp",
  "./media/Dumbbell_Bench_Press/0.webp",
  "./media/Dumbbell_Bench_Press/1.webp",
  "./media/videos/db-press.mp4",
  "./media/videos/db-press.webp",
  "./media/Dumbbell_Floor_Press/0.webp",
  "./media/Dumbbell_Floor_Press/1.webp",
  "./media/Barbell_Bench_Press_-_Medium_Grip/0.webp",
  "./media/Barbell_Bench_Press_-_Medium_Grip/1.webp",
  "./media/videos/bb-press.mp4",
  "./media/videos/bb-press.webp",
  "./media/One-Arm_Dumbbell_Row/0.webp",
  "./media/One-Arm_Dumbbell_Row/1.webp",
  "./media/Bent_Over_Barbell_Row/0.webp",
  "./media/Bent_Over_Barbell_Row/1.webp",
  "./media/Seated_Cable_Rows/0.webp",
  "./media/Seated_Cable_Rows/1.webp",
  "./media/videos/cable-row.mp4",
  "./media/videos/cable-row.webp",
  "./media/Wide-Grip_Lat_Pulldown/0.webp",
  "./media/Wide-Grip_Lat_Pulldown/1.webp",
  "./media/Pullups/0.webp",
  "./media/Pullups/1.webp",
  "./media/videos/pullup.mp4",
  "./media/videos/pullup.webp",
  "./media/Dumbbell_Shoulder_Press/0.webp",
  "./media/Dumbbell_Shoulder_Press/1.webp",
  "./media/videos/db-shoulder.mp4",
  "./media/videos/db-shoulder.webp",
  "./media/Side_Lateral_Raise/0.webp",
  "./media/Side_Lateral_Raise/1.webp",
  "./media/videos/lateral.mp4",
  "./media/videos/lateral.webp",
  "./media/Hammer_Curls/0.webp",
  "./media/Hammer_Curls/1.webp",
  "./media/videos/curl.mp4",
  "./media/videos/curl.webp",
  "./media/Bodyweight_Squat/0.webp",
  "./media/Bodyweight_Squat/1.webp",
  "./media/Goblet_Squat/0.webp",
  "./media/Goblet_Squat/1.webp",
  "./media/Dumbbell_Squat/0.webp",
  "./media/Dumbbell_Squat/1.webp",
  "./media/Barbell_Full_Squat/0.webp",
  "./media/Barbell_Full_Squat/1.webp",
  "./media/Barbell_Deadlift/0.webp",
  "./media/Barbell_Deadlift/1.webp",
  "./media/Butt_Lift_Bridge/0.webp",
  "./media/Butt_Lift_Bridge/1.webp",
  "./media/Leg_Press/0.webp",
  "./media/Leg_Press/1.webp",
  "./media/videos/legpress.mp4",
  "./media/videos/legpress.webp",
  "./media/Leg_Extensions/0.webp",
  "./media/Leg_Extensions/1.webp",
  "./media/Lying_Leg_Curls/0.webp",
  "./media/Lying_Leg_Curls/1.webp",
  "./media/videos/legcurl.mp4",
  "./media/videos/legcurl.webp",
  "./media/Dead_Bug/0.webp",
  "./media/Dead_Bug/1.webp",
  "./media/Plank/0.webp",
  "./media/Plank/1.webp",
  "./media/Farmers_Walk/0.webp",
  "./media/Farmers_Walk/1.webp",
  "./media/Cat_Stretch/0.webp",
  "./media/Cat_Stretch/1.webp",
  "./media/Rope_Jumping/0.webp",
  "./media/Rope_Jumping/1.webp",
  "./media/Incline_Dumbbell_Press/0.webp",
  "./media/Incline_Dumbbell_Press/1.webp",
  "./media/videos/incline.mp4",
  "./media/videos/incline.webp",
  "./media/Standing_Dumbbell_Triceps_Extension/0.webp",
  "./media/Standing_Dumbbell_Triceps_Extension/1.webp",
  "./media/videos/overhead-triceps.mp4",
  "./media/videos/overhead-triceps.webp",
  "./media/videos/rdl.mp4",
  "./media/videos/rdl.webp",
  "./media/Dumbbell_Rear_Lunge/0.webp",
  "./media/Dumbbell_Rear_Lunge/1.webp",
  "./media/Bicycling_Stationary/0.webp",
  "./media/Bicycling_Stationary/1.webp",
  "./media/Rowing_Stationary/0.webp",
  "./media/Rowing_Stationary/1.webp",
  "./media/Kneeling_Hip_Flexor/0.webp",
  "./media/Kneeling_Hip_Flexor/1.webp",
  "./media/90_90_Hamstring/0.webp",
  "./media/90_90_Hamstring/1.webp",
  "./media/Bench_Dips/0.webp",
  "./media/Bench_Dips/1.webp",
  './personal-engine.js',
  './personal-programs.js',
  './personal-nutrition.js',
  './player-profile.js',
  './athletic-profile.js',
  './basket-pathway.js',
  './basket-qi.js',
  './program-data.js',
  './media/ATTRIBUTION.md',
  './vendor/react.production.min.js',
  './vendor/react-dom.production.min.js'
];
// Illustrations du catalogue : mises en cache en arrière-plan après l'activation, jamais attendues à l'installation.
// Sans cela, la première ouverture après une mise à jour télécharge des dizaines de Mo avant d'être utilisable.
const PRECACHE_MEDIA = [
  './media/cards/wall-pushup.webp',
  './media/cards/band-row.webp',
  './media/cards/knee-pushup.webp',
  './media/cards/decline-pushup.webp',
  './media/generated/decline-pushup/0.webp',
  './media/generated/decline-pushup/1.webp',
  './media/cards/wide-pushup.webp',
  './media/generated/wide-pushup/0.webp',
  './media/generated/wide-pushup/1.webp',
  './media/cards/tempo-pushup.webp',
  './media/generated/tempo-pushup/0.webp',
  './media/generated/tempo-pushup/1.webp',
  './media/cards/scap-pushup.webp',
  './media/generated/scap-pushup/0.webp',
  './media/generated/scap-pushup/1.webp',
  './media/cards/pike-pushup.webp',
  './media/generated/pike-pushup/0.webp',
  './media/generated/pike-pushup/1.webp',
  './media/cards/band-pushup.webp',
  './media/generated/band-pushup/0.webp',
  './media/generated/band-pushup/1.webp',
  './media/cards/band-press.webp',
  './media/generated/band-press/0.webp',
  './media/generated/band-press/1.webp',
  './media/generated/knee-pushup/0.webp',
  './media/generated/knee-pushup/1.webp',
  './media/cards/bird-dog.webp',
  './media/generated/bird-dog/0.webp',
  './media/generated/bird-dog/1.webp',
  './media/cards/front-raise.webp',
  './media/generated/front-raise/0.webp',
  './media/generated/front-raise/1.webp',
  './media/cards/reverse-lunge.webp',
  './media/cards/db-lunge.webp',
  './media/cards/rdl.webp',
  './media/cards/kb-deadlift.webp',
  './media/cards/calf.webp',
  './media/cards/bike-interval.webp',
  './media/cards/walk.webp',
  './media/cards/run.webp',
  './media/cards/march.webp',
  './media/cards/stepjack.webp',
  './media/cards/hip-flexor.webp',
  './media/cards/shoulder-mob.webp',
  './media/cards/landing.webp',
  './media/cards/pogo.webp',
  './media/cards/lateral-hop.webp',
  './media/cards/band-shuffle.webp',
  './media/cards/halo.webp',
  './media/cards/triceps.webp',
  './media/cards/side-plank.webp',
  './media/cards/pallof.webp',
  './media/cards/ankle-mob.webp',
  './media/cards/thoracic.webp',
  './media/cards/copenhagen.webp',
  './media/cards/kb-swing.webp',
  './media/cards/breath.webp',
  './media/cards/defense.webp',
  './media/cards/vest-pushup.webp',
  './media/generated/vest-pushup/0.webp',
  './media/generated/vest-pushup/1.webp',
  './media/cards/slider-ham-curl.webp',
  './media/generated/slider-ham-curl/0.webp',
  './media/generated/slider-ham-curl/1.webp',
  './media/cards/spanish-squat.webp',
  './media/generated/spanish-squat/0.webp',
  './media/generated/spanish-squat/1.webp',
  './media/cards/cable-fly.webp',
  './media/generated/cable-fly/0.webp',
  './media/generated/cable-fly/1.webp',
  './media/cards/push-press.webp',
  './media/generated/push-press/0.webp',
  './media/generated/push-press/1.webp',
  './media/cards/diamond-pushup.webp',
  './media/generated/diamond-pushup/0.webp',
  './media/generated/diamond-pushup/1.webp',
  './media/cards/kb-press.webp',
  './media/generated/kb-press/0.webp',
  './media/generated/kb-press/1.webp',
  './media/cards/neutral-pullup.webp',
  './media/generated/neutral-pullup/0.webp',
  './media/generated/neutral-pullup/1.webp',
  './media/cards/dead-hang.webp',
  './media/generated/dead-hang/0.webp',
  './media/generated/dead-hang/1.webp',
  './media/cards/bb-row-underhand.webp',
  './media/generated/bb-row-underhand/0.webp',
  './media/generated/bb-row-underhand/1.webp',
  './media/cards/kb-row.webp',
  './media/generated/kb-row/0.webp',
  './media/generated/kb-row/1.webp',
  './media/cards/chest-supported-row.webp',
  './media/generated/chest-supported-row/0.webp',
  './media/generated/chest-supported-row/1.webp',
  './media/cards/cable-row-single.webp',
  './media/generated/cable-row-single/0.webp',
  './media/generated/cable-row-single/1.webp',
  './media/cards/facepull.webp',
  './media/generated/facepull/0.webp',
  './media/generated/facepull/1.webp',
  './media/cards/shrug.webp',
  './media/generated/shrug/0.webp',
  './media/generated/shrug/1.webp',
  './media/cards/bulgarian.webp',
  './media/generated/bulgarian/0.webp',
  './media/generated/bulgarian/1.webp',
  './media/cards/lateral-lunge.webp',
  './media/generated/lateral-lunge/0.webp',
  './media/generated/lateral-lunge/1.webp',
  './media/cards/cossack.webp',
  './media/generated/cossack/0.webp',
  './media/generated/cossack/1.webp',
  './media/cards/curtsy-lunge.webp',
  './media/generated/curtsy-lunge/0.webp',
  './media/generated/curtsy-lunge/1.webp',
  './media/cards/wall-sit.webp',
  './media/generated/wall-sit/0.webp',
  './media/generated/wall-sit/1.webp',
  './media/cards/band-squat.webp',
  './media/generated/band-squat/0.webp',
  './media/generated/band-squat/1.webp',
  './media/cards/assisted-pistol.webp',
  './media/generated/assisted-pistol/0.webp',
  './media/generated/assisted-pistol/1.webp',
  './media/cards/legpress-single.webp',
  './media/generated/legpress-single/0.webp',
  './media/generated/legpress-single/1.webp',
  './media/cards/single-rdl.webp',
  './media/generated/single-rdl/0.webp',
  './media/generated/single-rdl/1.webp',
  './media/cards/kb-rdl.webp',
  './media/generated/kb-rdl/0.webp',
  './media/generated/kb-rdl/1.webp',
  './media/cards/band-hinge.webp',
  './media/generated/band-hinge/0.webp',
  './media/generated/band-hinge/1.webp',
  './media/cards/hip-thrust.webp',
  './media/generated/hip-thrust/0.webp',
  './media/generated/hip-thrust/1.webp',
  './media/cards/nordic-assisted.webp',
  './media/generated/nordic-assisted/0.webp',
  './media/generated/nordic-assisted/1.webp',
  './media/cards/db-calf.webp',
  './media/generated/db-calf/0.webp',
  './media/generated/db-calf/1.webp',
  './media/cards/calf-hold.webp',
  './media/generated/calf-hold/0.webp',
  './media/generated/calf-hold/1.webp',
  './media/cards/band-curl.webp',
  './media/generated/band-curl/0.webp',
  './media/generated/band-curl/1.webp',
  './media/cards/db-kickback.webp',
  './media/generated/db-kickback/0.webp',
  './media/generated/db-kickback/1.webp',
  './media/cards/grip-hold.webp',
  './media/generated/grip-hold/0.webp',
  './media/generated/grip-hold/1.webp',
  './media/cards/hollow-hold.webp',
  './media/generated/hollow-hold/0.webp',
  './media/generated/hollow-hold/1.webp',
  './media/cards/plank-reach.webp',
  './media/generated/plank-reach/0.webp',
  './media/generated/plank-reach/1.webp',
  './media/cards/side-plank-lift.webp',
  './media/generated/side-plank-lift/0.webp',
  './media/generated/side-plank-lift/1.webp',
  './media/cards/bear-hold.webp',
  './media/generated/bear-hold/0.webp',
  './media/generated/bear-hold/1.webp',
  './media/cards/bear-crawl.webp',
  './media/generated/bear-crawl/0.webp',
  './media/generated/bear-crawl/1.webp',
  './media/cards/leg-raise.webp',
  './media/generated/leg-raise/0.webp',
  './media/generated/leg-raise/1.webp',
  './media/cards/cable-crunch.webp',
  './media/generated/cable-crunch/0.webp',
  './media/generated/cable-crunch/1.webp',
  './media/cards/suitcase-carry.webp',
  './media/generated/suitcase-carry/0.webp',
  './media/generated/suitcase-carry/1.webp',
  './media/cards/overhead-carry.webp',
  './media/generated/overhead-carry/0.webp',
  './media/generated/overhead-carry/1.webp',
  './media/cards/single-leg-stand.webp',
  './media/generated/single-leg-stand/0.webp',
  './media/generated/single-leg-stand/1.webp',
  './media/cards/single-leg-eyes.webp',
  './media/generated/single-leg-eyes/0.webp',
  './media/generated/single-leg-eyes/1.webp',
  './media/cards/single-leg-reach.webp',
  './media/generated/single-leg-reach/0.webp',
  './media/generated/single-leg-reach/1.webp',
  './media/cards/tandem-stand.webp',
  './media/generated/tandem-stand/0.webp',
  './media/generated/tandem-stand/1.webp',
  './media/cards/heel-toe-walk.webp',
  './media/generated/heel-toe-walk/0.webp',
  './media/generated/heel-toe-walk/1.webp',
  './media/cards/airplane.webp',
  './media/generated/airplane/0.webp',
  './media/generated/airplane/1.webp',
  './media/cards/clamshell.webp',
  './media/generated/clamshell/0.webp',
  './media/generated/clamshell/1.webp',
  './media/cards/hip-abduction.webp',
  './media/generated/hip-abduction/0.webp',
  './media/generated/hip-abduction/1.webp',
  './media/cards/squat-thrust.webp',
  './media/generated/squat-thrust/0.webp',
  './media/generated/squat-thrust/1.webp',
  './media/cards/burpee-nojump.webp',
  './media/generated/burpee-nojump/0.webp',
  './media/generated/burpee-nojump/1.webp',
  './media/cards/burpee.webp',
  './media/generated/burpee/0.webp',
  './media/generated/burpee/1.webp',
  './media/cards/skater.webp',
  './media/generated/skater/0.webp',
  './media/generated/skater/1.webp',
  './media/cards/shadow-box.webp',
  './media/generated/shadow-box/0.webp',
  './media/generated/shadow-box/1.webp',
  './media/cards/stair.webp',
  './media/generated/stair/0.webp',
  './media/generated/stair/1.webp',
  './media/cards/walk-hill.webp',
  './media/generated/walk-hill/0.webp',
  './media/generated/walk-hill/1.webp',
  './media/cards/run-interval.webp',
  './media/generated/run-interval/0.webp',
  './media/generated/run-interval/1.webp',
  './media/cards/rower-interval.webp',
  './media/generated/rower-interval/0.webp',
  './media/generated/rower-interval/1.webp',
  './media/cards/depth-drop.webp',
  './media/generated/depth-drop/0.webp',
  './media/generated/depth-drop/1.webp',
  './media/cards/worlds-greatest.webp',
  './media/generated/worlds-greatest/0.webp',
  './media/generated/worlds-greatest/1.webp',
  './media/cards/downdog.webp',
  './media/generated/downdog/0.webp',
  './media/generated/downdog/1.webp',
  './media/cards/pigeon.webp',
  './media/generated/pigeon/0.webp',
  './media/generated/pigeon/1.webp',
  './media/cards/deep-squat-hold.webp',
  './media/generated/deep-squat-hold/0.webp',
  './media/generated/deep-squat-hold/1.webp',
  './media/cards/doorway-chest.webp',
  './media/generated/doorway-chest/0.webp',
  './media/generated/doorway-chest/1.webp',
  './media/cards/band-dislocate.webp',
  './media/generated/band-dislocate/0.webp',
  './media/generated/band-dislocate/1.webp',
  './media/cards/quad-rotation.webp',
  './media/generated/quad-rotation/0.webp',
  './media/generated/quad-rotation/1.webp',
  './media/cards/wrist-mob.webp',
  './media/generated/wrist-mob/0.webp',
  './media/generated/wrist-mob/1.webp',
  './media/cards/tke.webp',
  './media/generated/tke/0.webp',
  './media/generated/tke/1.webp',
  './media/cards/iso-split.webp',
  './media/generated/iso-split/0.webp',
  './media/generated/iso-split/1.webp',
  './media/cards/step-down.webp',
  './media/generated/step-down/0.webp',
  './media/generated/step-down/1.webp',
  './media/cards/wall-drill.webp',
  './media/generated/wall-drill/0.webp',
  './media/generated/wall-drill/1.webp',
  './media/cards/accel-10.webp',
  './media/generated/accel-10/0.webp',
  './media/generated/accel-10/1.webp',
  './media/cards/sprint-20.webp',
  './media/generated/sprint-20/0.webp',
  './media/generated/sprint-20/1.webp',
  './media/cards/crossover-start.webp',
  './media/generated/crossover-start/0.webp',
  './media/generated/crossover-start/1.webp',
  './media/cards/shuttle-5105.webp',
  './media/generated/shuttle-5105/0.webp',
  './media/generated/shuttle-5105/1.webp',
  './media/cards/decel-stick.webp',
  './media/generated/decel-stick/0.webp',
  './media/generated/decel-stick/1.webp',
  './media/cards/lateral-bound-stick.webp',
  './media/generated/lateral-bound-stick/0.webp',
  './media/generated/lateral-bound-stick/1.webp',
  './media/cards/single-hop-stick.webp',
  './media/generated/single-hop-stick/0.webp',
  './media/generated/single-hop-stick/1.webp',
  './media/cards/foot-doming.webp',
  './media/generated/foot-doming/0.webp',
  './media/generated/foot-doming/1.webp',
  './media/cards/vest-pullup.webp',
  './media/generated/vest-pullup/0.webp',
  './media/generated/vest-pullup/1.webp',
  './media/cards/vest-split-squat.webp',
  './media/generated/vest-split-squat/0.webp',
  './media/generated/vest-split-squat/1.webp',
  './media/cards/vest-step-up.webp',
  './media/generated/vest-step-up/0.webp',
  './media/generated/vest-step-up/1.webp',
  './media/cards/vest-calf.webp',
  './media/generated/vest-calf/0.webp',
  './media/generated/vest-calf/1.webp',
  './media/cards/slider-lateral-lunge.webp',
  './media/generated/slider-lateral-lunge/0.webp',
  './media/generated/slider-lateral-lunge/1.webp',
  './media/cards/slider-reverse-lunge.webp',
  './media/generated/slider-reverse-lunge/0.webp',
  './media/generated/slider-reverse-lunge/1.webp',
  './media/cards/slider-climber.webp',
  './media/generated/slider-climber/0.webp',
  './media/generated/slider-climber/1.webp',
  './media/cards/slider-adductor.webp',
  './media/generated/slider-adductor/0.webp',
  './media/generated/slider-adductor/1.webp',
  './media/cards/slider-bodysaw.webp',
  './media/generated/slider-bodysaw/0.webp',
  './media/generated/slider-bodysaw/1.webp',
  './media/cards/er-iso.webp',
  './media/generated/er-iso/0.webp',
  './media/generated/er-iso/1.webp',
  './media/cards/wall-slide.webp',
  './media/generated/wall-slide/0.webp',
  './media/generated/wall-slide/1.webp',
  './media/cards/curl-up.webp',
  './media/generated/curl-up/0.webp',
  './media/generated/curl-up/1.webp',
  './media/cards/heel-drop-ecc.webp',
  './media/generated/heel-drop-ecc/0.webp',
  './media/generated/heel-drop-ecc/1.webp',
  './media/cards/finger-ext.webp',
  './media/generated/finger-ext/0.webp',
  './media/generated/finger-ext/1.webp',
  './media/cards/chin-tuck.webp',
  './media/generated/chin-tuck/0.webp',
  './media/generated/chin-tuck/1.webp',
  './media/cards/towel-grip.webp',
  './media/generated/towel-grip/0.webp',
  './media/generated/towel-grip/1.webp',
  './media/cards/ankle-alphabet.webp',
  './media/generated/ankle-alphabet/0.webp',
  './media/generated/ankle-alphabet/1.webp',
  './media/cards/jog-court.webp',
  './media/generated/jog-court/0.webp',
  './media/generated/jog-court/1.webp',
  './media/cards/lateral-shuffle.webp',
  './media/generated/lateral-shuffle/0.webp',
  './media/generated/lateral-shuffle/1.webp',
  './media/cards/carioca.webp',
  './media/generated/carioca/0.webp',
  './media/generated/carioca/1.webp',
  './media/generated/band-row/0.webp',
  './media/generated/band-row/1.webp',
  './media/generated/calf/0.webp',
  './media/generated/calf/1.webp',
  './media/generated/kb-deadlift/0.webp',
  './media/generated/kb-deadlift/1.webp',
  './media/generated/landing/0.webp',
  './media/generated/landing/1.webp',
  './media/generated/lateral-hop/0.webp',
  './media/generated/lateral-hop/1.webp',
  './media/generated/march/0.webp',
  './media/generated/march/1.webp',
  './media/generated/pogo/0.webp',
  './media/generated/pogo/1.webp',
  './media/generated/reverse-lunge/0.webp',
  './media/generated/reverse-lunge/1.webp',
  './media/generated/run/0.webp',
  './media/generated/run/1.webp',
  './media/generated/shoulder-mob/0.webp',
  './media/generated/shoulder-mob/1.webp',
  './media/generated/stepjack/0.webp',
  './media/generated/stepjack/1.webp',
  './media/generated/walk/0.webp',
  './media/generated/walk/1.webp',
  './media/generated/wall-pushup/0.webp',
  './media/generated/wall-pushup/1.webp',
  './media/generated/band-shuffle/0.webp',
  './media/generated/band-shuffle/1.webp',
  './media/generated/halo/0.webp',
  './media/generated/halo/1.webp',
  './media/generated/triceps/0.webp',
  './media/generated/triceps/1.webp',
  './media/generated/side-plank/0.webp',
  './media/generated/side-plank/1.webp',
  './media/generated/pallof/0.webp',
  './media/generated/pallof/1.webp',
  './media/generated/ankle-mob/0.webp',
  './media/generated/ankle-mob/1.webp',
  './media/generated/thoracic/0.webp',
  './media/generated/thoracic/1.webp',
  './media/generated/copenhagen/0.webp',
  './media/generated/copenhagen/1.webp',
  './media/generated/kb-swing/0.webp',
  './media/generated/kb-swing/1.webp',
  './media/generated/breath/0.webp',
  './media/generated/breath/1.webp',
  './media/generated/defense/0.webp',
  './media/generated/defense/1.webp',
  './media/cards/a-march.webp',
  './media/generated/a-march/0.webp',
  './media/generated/a-march/1.webp',
  './media/cards/psoas-march.webp',
  './media/generated/psoas-march/0.webp',
  './media/generated/psoas-march/1.webp',
  './media/cards/falling-start.webp',
  './media/generated/falling-start/0.webp',
  './media/generated/falling-start/1.webp',
  './media/cards/split-start.webp',
  './media/generated/split-start/0.webp',
  './media/generated/split-start/1.webp',
  './media/cards/drop-step-start.webp',
  './media/generated/drop-step-start/0.webp',
  './media/generated/drop-step-start/1.webp',
  './media/cards/band-resisted-start.webp',
  './media/generated/band-resisted-start/0.webp',
  './media/generated/band-resisted-start/1.webp',
  './media/cards/snap-down.webp',
  './media/generated/snap-down/0.webp',
  './media/generated/snap-down/1.webp',
  './media/cards/single-pogo.webp',
  './media/generated/single-pogo/0.webp',
  './media/generated/single-pogo/1.webp',
  './media/cards/single-leg-vertical.webp',
  './media/generated/single-leg-vertical/0.webp',
  './media/generated/single-leg-vertical/1.webp',
  './media/cards/slant-squat.webp',
  './media/generated/slant-squat/0.webp',
  './media/generated/slant-squat/1.webp',
  './media/cards/a-skip.webp',
  './media/generated/a-skip/0.webp',
  './media/generated/a-skip/1.webp',
  './media/cards/knee-drive-iso.webp',
  './media/generated/knee-drive-iso/0.webp',
  './media/generated/knee-drive-iso/1.webp',
  './media/cards/vertical-jump.webp',
  './media/generated/vertical-jump/0.webp',
  './media/generated/vertical-jump/1.webp',
  './media/cards/drop-jump.webp',
  './media/generated/drop-jump/0.webp',
  './media/generated/drop-jump/1.webp',
  './media/cards/approach-jump.webp',
  './media/generated/approach-jump/0.webp',
  './media/generated/approach-jump/1.webp',
  './media/cards/db-jump.webp',
  './media/generated/db-jump/0.webp',
  './media/generated/db-jump/1.webp',
  './media/cards/lateral-decel.webp',
  './media/generated/lateral-decel/0.webp',
  './media/generated/lateral-decel/1.webp',
  './media/cards/reverse-nordic.webp',
  './media/generated/reverse-nordic/0.webp',
  './media/generated/reverse-nordic/1.webp',
  './media/cards/couch-stretch.webp',
  './media/generated/couch-stretch/0.webp',
  './media/generated/couch-stretch/1.webp',
  './media/cards/active-slr.webp',
  './media/generated/active-slr/0.webp',
  './media/generated/active-slr/1.webp',
  './media/pathway/1.webp',
  './media/pathway/2.webp',
  './media/pathway/3.webp',
  './media/pathway/4.webp',
  './media/pathway/5.webp'
];
const clipFetches = new Set();
// Only the app shell and its public libraries are cached. Account, profile and sync traffic must always hit the network.
const CACHEABLE_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];
// Le code de l'app (HTML, JS, CSS, manifeste) : réseau d'abord, pour ne jamais mélanger deux versions après un déploiement.
const isAppCode = url => url.origin === self.location.origin && /\.(js|css|json|html)$|\/$/.test(url.pathname) && !url.pathname.startsWith('/media/') && !url.pathname.startsWith('/vendor/');
const isMedia = u => u.includes('/media/') && !/\.(css|woff2|ttf|json|md)$/.test(u);
// Ne jamais lancer des dizaines de Mo de téléchargement quand l'utilisateur économise ses données.
const saveData = () => !!(self.navigator && navigator.connection && (navigator.connection.saveData || /(^|-)2g$/.test(navigator.connection.effectiveType || '')));

// Par lots : une rafale de centaines de requêtes simultanées sature le réseau d'un téléphone.
async function cacheInBatches(list, size) {
  const c = await caches.open(CACHE);
  for (let i = 0; i < list.length; i += size) {
    await Promise.all(list.slice(i, i + size).map(async u => {
      if (await c.match(u)) return;
      return c.add(u).catch(() => null);
    }));
  }
}

self.addEventListener('install', e => {
  // Le socle part d'un coup : l'app doit être contrôlée au plus vite.
  // Le socle est atomique : si un fichier de code manque, l'installation échoue et l'ancienne version reste active.
  // Seules les illustrations peuvent manquer sans bloquer.
  const core = PRECACHE.filter(u => !isMedia(u)), media = PRECACHE.filter(isMedia);
  e.waitUntil(
    caches.open(CACHE).then(c =>
      c.addAll(core.map(u => new Request(u, {cache: 'reload'})))
        .then(() => Promise.all(media.map(u => c.add(u).catch(() => null))))
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim()).then(() => saveData() ? null : cacheInBatches(PRECACHE_MEDIA, 12))
  );
});

// Navigation et code : réseau d'abord. Médias, polices et bibliothèques : cache avec mise à jour en arrière-plan.
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  const sameOrigin = url.origin === self.location.origin;
  if (!sameOrigin && !CACHEABLE_HOSTS.includes(url.hostname)) return;
  if (sameOrigin && url.pathname.startsWith('/api/')) return;

  // Native video players request byte ranges, including when seeking offline.
  if (e.request.headers.has('range') && /\.(mp4|webm)$/i.test(url.pathname)) {
    e.respondWith((async () => {
      const cached = await caches.match(e.request.url);
      if (!cached || cached.status !== 200) {
        // Extraits du QI vidéo : la première lecture passe par le réseau, le fichier entier est gardé pour les suivantes.
        if (sameOrigin && url.pathname.startsWith('/clips/') && !clipFetches.has(url.href)) {
          clipFetches.add(url.href);
          e.waitUntil(fetch(url.href).then(res => res.ok ? caches.open(CACHE).then(c => c.put(url.href, res)) : null).catch(() => {}).finally(() => clipFetches.delete(url.href)));
        }
        return fetch(e.request);
      }
      const buffer = await cached.arrayBuffer(), size = buffer.byteLength;
      const range = /^bytes=(\d*)-(\d*)$/.exec(e.request.headers.get('range'));
      if (!range || (!range[1] && !range[2])) return new Response(null, {status:416,headers:{'Content-Range':`bytes */${size}`}});
      const start = range[1] ? Number(range[1]) : Math.max(0,size-Number(range[2]));
      const end = range[1] && range[2] ? Math.min(size-1,Number(range[2])) : size-1;
      if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start> end || start>=size) return new Response(null, {status:416,headers:{'Content-Range':`bytes */${size}`}});
      return new Response(buffer.slice(start,end+1), {status:206,headers:{'Content-Type':cached.headers.get('Content-Type')||'video/mp4','Content-Length':String(end-start+1),'Content-Range':`bytes ${start}-${end}/${size}`,'Accept-Ranges':'bytes'}});
    })());
    return;
  }

  if (e.request.mode === 'navigate') {
    e.respondWith(
      fetch(e.request).then(res => {
        // Une page d'erreur (404, 500, portail Wi-Fi) ne doit jamais remplacer l'app hors connexion.
        if (res.ok && res.type === 'basic') {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put('./index.html', clone));
        }
        return res;
      }).catch(async () => {
        const cached = await caches.match('./index.html');
        if (!cached) return Response.error();
        // Static hosts can redirect /index.html to /. A redirected cached response
        // cannot satisfy a navigation in manual redirect mode, so rebuild it.
        return new Response(await cached.arrayBuffer(), {
          status: cached.status, statusText: cached.statusText, headers: cached.headers
        });
      })
    );
    return;
  }

  if (isAppCode(url)) {
    e.respondWith(
      fetch(e.request).then(res => {
        if (res.ok) {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return res;
      }).catch(async () => (await caches.match(e.request)) || Response.error())
    );
    return;
  }

  e.respondWith(
    caches.match(e.request).then(cached => {
      const fresh = fetch(e.request).then(res => {
        if (res && (res.status === 200 || res.type === 'opaque')) {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return res;
      }).catch(() => cached);
      return cached || fresh;
    })
  );
});
